### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [DeliasZen/grid-template#1]
1)
эффекты при наведении не выполнены
![image](https://user-images.githubusercontent.com/8464662/142631089-e814f6db-9a2a-47e8-b567-f340ec5d700a.png)

**Comment by DeliasZen** [comment]
Добрый день.
Действительно пропустил. Жаль, почти получилось с первого раза.

Направляю Вам исправленный вариант:

Git:  https://github.com/DeliasZen/grid-template.git
Git-Pages:  https://deliaszen.github.io/grid-template/


Подскажите, пожалуйста, конкретно в этом примере для добавления hover я
использовал теги внутри классов, такой вариант допустим или может быть есть
иной способ?

пт, 19 нояб. 2021 г. в 16:34, Andrey ***@***.***>:

**Comment by Alecto** [comment]
теперь отлично, принята.
кому ставить оценку?

сб, 20 лист. 2021 о 16:13 Ilya Shutikov ***@***.***> пише:

> Добрый день.
> Действительно пропустил. Жаль, почти получилось с первого раза.
>
> Направляю Вам исправленный вариант:
>
> Git: https://github.com/DeliasZen/grid-template.git
> Git-Pages: https://deliaszen.github.io/grid-template/
>
>
> Подскажите, пожалуйста, конкретно в этом примере для добавления hover я
> использовал теги внутри классов, такой вариант допустим или может быть
> есть
> иной способ?

что вас смущает?

**Comment by DeliasZen** [comment]
Прошу прощения, не обратил внимания, что тема письма была изменена: SkillUp
FrontEnd. Шутиков Илья, вт/чт 20:15. (grid-template)

Смущает, что на первых уроках оговаривалось, что работать в css необходимо
исключительно с классами.

сб, 20 нояб. 2021 г. в 21:00, Andrey ***@***.***>:

**Comment by Alecto** [comment]
хорошо, работу отметил

>
